### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [newb-dev-1008/CoVID_Entertainment_Impact#9]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/ABHGYM
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by newb-dev-1008** [comment]
Hi, 
Firstly, thank you for adding my compiled datasets as a part of your common COVID-19 DataFrame. I'm glad to be of some help to my fellow data analysts.
Since this is data pertaining to the impact on the Entertainment Industry due to the pandemic, I doubt it will be of help to the medical community for COVID-19 analysis. I'm fine with the inclusion of my datasets in the common forum, but I will be unable to constantly update it due to the following reasons:
- I had scraped and munged data from written official reports and dossiers. And since reports are released only on a periodical basis, data will be inconsistent and not as authentic as the original dataset.
- The datasets are a month old already, and there are no credible sources that can provide updated data without any adulteration.
- Since this project has been completed, I have left it as a read-only manuscript. I will not be making further changes to the dataset or to the iPython notebook.
